version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "deps"
    labels:
      - dependencies
      - dotnet
    open-pull-requests-limit: 10
    groups:
      nuget-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "ci"
    labels:
      - dependencies
      - ci
    open-pull-requests-limit: 5
    groups:
      actions-all:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /segment_reporting
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "deps(js)"
    labels:
      - dependencies
      - javascript
    open-pull-requests-limit: 5
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch
